#version: '3.1'
#
#services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_DB: "Comic_shop"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "1"
#    ports:
#      - 5432:5432
#    volumes:
#      - ./src/main/resources/SQL:/docker-entrypoint-initdb.d
#  spring_app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Comic_shop
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=1
#    depends_on:
#      - db
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 5433:5433