#version: '3.1'
#
#services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_DB: "Comic_shop"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "1"
#    ports:
#      - 5432:5432
#    volumes:
#      - ./src/main/resources/SQL:/docker-entrypoint-initdb.d
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 5433:5433