spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://batyr.db.elephantsql.com:5432/ygsoxkii
    username: "ygsoxkii"
    password: "8NKZTa_ZUyXlyeyjBc1G2XTCiJZYRU5a"

  #    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/Comic_shop
#    username: postgres
#    password: 1

  liquibase:
    change-log: classpath:liquibase.changelog/db-changelog.yml

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie